# .streamlit/secrets.toml

groq_api_key = "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"

chatvolt_api_key = "1f1fe62e-7761-445f-acb2-efb3b4f26306"
chatvolt_agent_id = "cm9cpkifv0pdrj1j5bxui5651"